name: build
on:
  push:
    branches: [master]

jobs:
  build-linux:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build goldboot image
        uses: fossable/goldboot-action@master
        with:
          output: image.gb

      - name: Save image artifact
        uses: actions/upload-artifact@v3
        with:
          name: my_image.gb
          path: image.gb
